on:
  push:
    branches:
      - init
      - main

permissions:
  contents: write
  pull-requests: write

name: release

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@v4
        with:
          token: ${{ secrets.GH_TOKEN }}
          skip-github-release: false
          skip-github-pull-request: true
          release-type: simple
