# https://github.com/docker/metadata-action/tree/v5/?tab=readme-ov-file#semver
name: create-release

on:
  push:
  #   branches:
  #     - 'master'
  #   tags:
  #     - 'v*'
  # pull_request:
  #   branches:
  #     - 'master'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: post result back to PR as comment
        uses: actions/github-script@v7
        with:
          script: |
              github.rest.issues.createComment({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: '${{steps.pr_run.outputs.pr_comment}}'
              })
