on:
  push:
    branches:
      - init
      - main

permissions:
  contents: write
  pull-requests: write

name: release

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@v4
        with:
          token: ${{ secrets.GH_TOKEN }}
          skip-github-pull-request: true
          # this is a built-in strategy in release-please, see "Action Inputs"
          # for more options
          release-type: simple
