on:
  push:
    branches:
      - init
      - main

permissions:
  contents: write
  pull-requests: write

name: release8
jobs:
  release8:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Bump version and push tag
        uses: hennejg/github-tag-action@v4.3.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}