#https://github.com/marketplace/actions/action-for-semantic-release
on:
  push:
    branches:
      - init
      - main

permissions:
  contents: write
  pull-requests: write

name: release2

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v4
        with: 
          ci: true
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

