# https://github.com/marketplace/actions/git-semantic-version
on:
  push:
    branches:
      - init
      - main

permissions:
  contents: write
  pull-requests: write

name: release3

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - name: Application Version
        id: version
        uses: paulhatch/semantic-version@v5.4.0
        with:
          change_path: "src/service"