# https://github.com/PaulHatch/semantic-version/blob/master/readme.md

name: release3
on:
  push:
    # branches:
    #   - main

# permissions:
#   contents: write
#   pull-requests: write
permissions:
  contents: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Semantic Version
        id: sver
        uses: paulhatch/semantic-version@v5.4.0
        with:
          major_pattern: "major"
          minor_pattern: "minor"
          version_format: "${major}.${minor}.${patch}"
          tag_prefix: "v"

      - name: Use results
        run: |
          echo "version is ${{ steps.sver.outputs.version }}"
          echo "version_tag is ${{ steps.sver.outputs.version_tag }}"
          echo "previous_version is ${{ steps.sver.outputs.previous_version }}"

      - name: Create Release
        id: create_release
        uses:  ncipollo/release-action@v1.16.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
          TAG: ${{ steps.sver.outputs.version_tag }}
        with:
          tag: ${{ env.tag }}
          name: ${{ env.tag }}
          draft: false
          prerelease: false

      # - name: Update PR
      #   uses: actions/github-script@v7

      #   with:
      #     github-token: ${{ secrets.GITHUB_TOKEN }}
      #     script: |
      #       const fs = require("fs");